version: '3.9'

services:
  db:
    image: postgres
    env_file:
      - .env
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8999"
    volumes:
      - .:/app
    ports:
      - "8999:8999"
    depends_on:
      - db
    env_file:
      - .env